apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::767397667940:user/Terraform
      username: Terraform
      groups:
        - system:masters
